### ISSUE TITLE
assurances data: Wrong state merklization for storage (assurances, block 1_004)

### ISSUE THREAD

**Issue by dakk** [jam-duna/jamtestnet#86]
Account storage for service 0 is encoded as "0x008100e4007a0019e6b29b0a65b9591762ce5143ed30d0261e5d24a320175250", while the formula is the following:

![Image](https://github.com/user-attachments/assets/f085ad91-87d1-4f2c-88d9-25b5cd648065)

So, in theory, since 2**32-1 is 0xffffff and service id is 0x000000, the first bytes should to be 0x00ff00ff00ff00ff.

**Comment by sourabhniyogi** [comment]
Will post a derivation after a new update!

**Comment by sourabhniyogi** [comment]
We agree with your derivation, we still had some 0.4.x code around... will update!

```
ComputeC_sh(s=0, h=0xffffffff00000000000000000000000000000000000000000000000000000000)=00ff00ff00ff00ff000000000000000000000000000000000000000000000000
```

**Comment by dakk** [comment]
> We agree with your derivation, we still had some 0.4.x code around... will update!
> 
> ```
> ComputeC_sh(s=0, h=0xffffffff00000000000000000000000000000000000000000000000000000000)=00ff00ff00ff00ff000000000000000000000000000000000000000000000000
> ```

I suspected it (y) You may find my tool jambiato useful in those situation; you can tag GP version/formula on your code, and check if there's something outdated: https://github.com/dakk/jambiato

**Comment by sourabhniyogi** [comment]
fixed [in 0.6.2.4](https://github.com/jam-duna/jamtestnet/blob/0.6.2.4/data/assurances/state_transitions/1_004.json#L206)

**Comment by dakk** [comment]
This is still wrong in my opinion; this would be correct if "k" is a zero hash

![Image](https://github.com/user-attachments/assets/ab6f1442-6587-41af-9e11-c7ab46e7b6e2)

**Comment by sourabhniyogi** [comment]
We have k as `00000000` [here](https://github.com/jam-duna/jamtestnet/blob/main/assurances.txt#L9) and padded to a zero hash.  

```
SetServiceStorage(s=0, k=00000000, v=63803b10) C(s, concat(0xFFFFFFFF,k[0:28])=0xffffffff00000000000000000000000000000000000000000000000000000000)=00ff00ff00ff00ff000000000000000000000000000000000000000000000000
```

**Comment by jaymansfield** [comment]
> We have k as `00000000` [here](https://github.com/jam-duna/jamtestnet/blob/main/assurances.txt#L9) and padded to a zero hash.
> 
> ```
> SetServiceStorage(s=0, k=00000000, v=63803b10) C(s, concat(0xFFFFFFFF,k[0:28])=0xffffffff00000000000000000000000000000000000000000000000000000000)=00ff00ff00ff00ff000000000000000000000000000000000000000000000000
> ```
> 
> but I see we missed [this hash](https://graypaper.fluffylabs.dev/#/293bf5a/2d70012d7001) so you are right..

I get a different value for k see https://github.com/jam-duna/jamtestnet/issues/74#issuecomment-2676175805

**Comment by sourabhniyogi** [comment]
> > 
> 
> I get a different value for k see [#74 (comment)](https://github.com/jam-duna/jamtestnet/issues/74#issuecomment-2676175805)

We are in agreement -- 
https://github.com/jam-duna/jamtestnet/blob/main/data/assurances/state_transitions/1_004.json#L206-L207
